LICENSE file check is unnecessary

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -90,14 +90,11 @@ jobs:
       - name: Check for UW License Headers
         shell: bash
         run: |
-          if [[ -f "./LICENSE" ]]; then
-            LICENSE_ERR=$(find ${DJANGO_APP} -type f -size +0 -not -path "*/migrations/*" -not -path "*/org_filters/*" -not -path "dispatch.py" -name "*.py"\
-              -exec grep -PzL "# Copyright $(date +'%Y') University of Washington\n# SPDX-License-Identifier: Apache-2.0 {} \;)
-            if [[ ! -z $LICENSE_ERR ]]; then
-              echo "Missing License or Copyright information:"
-              echo "$LICENSE_ERR"
-              exit 1
-            fi
+          LICENSE_ERR=$(find ${DJANGO_APP} -type f -size +0 -not -path "*/migrations/*" -not -path "*/org_filters/*" -not -path "dispatch.py" -name "*.py" -exec grep -PzL "# Copyright $(date +'%Y') University of Washington\n# SPDX-License-Identifier: Apache-2.0 {} \;)
+          if [[ ! -z $LICENSE_ERR ]]; then
+            echo "Missing License or Copyright information:"
+            echo "$LICENSE_ERR"
+            exit 1
           fi
 
       - name: Set up Docker Buildx
